name: notesense
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  bloc: ^8.1.2
  build_runner: ^2.4.7
  dartz: ^0.10.1
  dio: ^5.3.4
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_image_stack: ^0.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  glass_kit: ^3.0.0
  heroicons: ^0.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.18.0
  introduction_screen: ^3.1.12
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  retry: ^3.1.2

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
  assets:
    - .env
    - assets/images/
    - assets/fonts/
